<h1 id="slog">Slog</h1>
<p>Slog is a work I have done for college assignment IF3110 Web-Based Development <a href="https://github.com/if-itb/IF3110-01-Simple-Blog">Simple Blog</a>.</p>
<p>Please note that the website design and structure is still <em>very very</em> unsafe and <strong>should not be used directly without modification</strong>. For example, the post and comment feature are very prone to malicious HTML injection. After all, Slog is only created in a week from a blank folder by a drunk programmer for a college assignment -- surely you shouldn't expect much.</p>
<h2 id="structure">Structure</h2>
<ul>
<li><code>index.php</code>: the main request handler.</li>
<li><code>css/style.css</code>: contains the stylesheet for the website. I generated the stylesheet using <a href="http://lesscss.org/">LESS</a>. The LESS files is available at <code>css/less</code> folder.</li>
<li><code>js/script.js</code>: contains the web page script for the website.</li>
<li><code>php</code>: contains the PHP files.<ul>
<li><code>php/action</code>: contains form requests handlers.</li>
<li><code>php/ajax</code>: contains AJAX requests handlers.</li>
<li><code>php/crud</code>: contains functions to retrieve, update, and delete posts and comments.</li>
<li><code>php/lib</code>: contains helper functions to access database and creating URLs.</li>
<li><code>php/pages</code>: contains pages that can be accessed using <code>?p=<page_name></code>.</li>
<li><code>php/templates</code>: contains templates for views.</li>
<li><code>php/views</code>: contains views that will be shown to user.</li>
<li><code>php/config.php</code>: contains the configuration variables for the website.</li>
</ul>
</li>
</ul>
<h2 id="notes">Notes</h2>
<p>The web page content is generated by <code>index.php</code>, which will use the correct view or do correct actions based on the value of <code>GET</code> parameters. The internal design uses <code>require</code> directive available in PHP. This design was partially inspired by <a href="https://ellislab.com/codeigniter">CodeIgniter</a>. This allows URL rewriting (depends on the server) and easier MVC design.</p>
<p>This website depends on MySQLi feature available in the PHP interpreter, which should be for most PHP-based web servers. The configurations (user name, password, database name, database server) are available at <code>config.php</code>. A sample SQL database dump is provided at <code>slog.sql</code>.</p>
<h2 id="license">License</h2>
<p>Slog is licensed under MIT License.</p>
<hr>
<p>Feel free to contact me at <a href="https://twitter.com/tkesgar">@tkesgar</a> about this project.</p>
